### ISSUE TITLE
Example project not compatible with Django 3.2

### ISSUE THREAD

**Issue by infosrabah** [adamghill/django-unicorn#192]
Got an error ater installing django-unicorn, head towards example project,  and

python manage.py runserver

I got this error :
```
django.core.exceptions.ImproperlyConfigured: Cannot import 'example.books'. Check that 'books.apps.Config.name' is correct.
```

thank you

**Comment by infosrabah** [comment]
You welcome.

ALSO why is there a lot of package dependencies??


On Saturday, April 24, 2021, Adam Hill ***@***.***> wrote:
> Thanks for the issue, I'll take a look into this ASAP.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/rxs_Au6RusLcfkrORxLbe-zsq8g97Jd4zYnKTrP3yJfN2gM5a05ctZYMNTd5zUEsD_XGfKuRyGNxEDLg_bqMcBVT_kus2_UmC0DYS-_4yuGT792yAG23aR7omVwIIIlnVOeCzzHSgnmWAJjSM403IP4Y9QZbtIPDJwehvkJ6vQ8e0eHIn_3KZHtFbXAERjtMnEOMRbN3ahzzxPNK99u43THlzziPXPWVxKY4S2vneQ=s0-d-e1-ft#https://github.com/notifications/beacon/AIHQR3WUCD6MXCPZGF4MOJ3TKIRU7A5CNFSM43PRRUZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGE6ARUQ.gif>

**Comment by mbacicc** [comment]
I’m using it on django 3.2 and it works properly. Can you explain in more details your install procedure?

**Comment by adamghill** [comment]
I fixed the tests for 3.2 in b94b840, but the example project starts up for me on Django 3.2, as well. From the root of the project, I run something like `poetry run example/manage.py runserver 0:8080`, is that what you are doing? Also, just in case, what version of Python are you on? Thanks.

>ALSO why is there a lot of package dependencies

I'm not sure what you mean by "a lot". :) Feel free to look through the code and you can see where any dependency is used. If you have a question about one specifically, let me know.

**Comment by adamghill** [comment]
I'm going to close this for now, but feel free to re-open if the example project still won't work.

**Comment by infosrabah** [comment]
still the same error as above,

and here my pip3 freeze, for the dependency :
asgiref==3.3.4
beautifulsoup4==4.9.3
cachetools==4.2.1
decorator==4.4.2
Django==3.2
django-unicorn==0.27.1
orjson==3.5.2
pytz==2021.1
shortuuid==1.0.1
soupsieve==2.2.1
sqlparse==0.4.1
typing-extensions==3.7.4.3

I thought project needs just django and django-unicorn, beside django dependency as sqlparse, pytz, asgiref

so why : 
```
soupsieve==2.2.1
typing-extensions==3.7.4.3
orjson==3.5.2
decorator==4.4.2
cachetools==4.2.1
beautifulsoup4==4.9.3
```
thank you
